### ISSUE TITLE
Preview button greyed out for Lab 2.2: Create a unified customer profile

### ISSUE THREAD

**Issue by Skillable-MelieKrichko** [MicrosoftLearning/MB-280T03-Design-and-deliver-powerful-customer-experiences-with-Dynamics-365-Customer-Insights#1] opened 2024-11-18 15:33 UTC
# Module: Lab 2.2: Create a unified customer profile
#### Step: 04

Description of issue

The Preview button is required for steps 4 and 7 but it is showing as greyed out. 

![image](https://github.com/user-attachments/assets/a0166a45-03a3-4f81-b8ed-e2a2336b1e78)

![image](https://github.com/user-attachments/assets/21cac535-30ae-458e-bedc-4a0713e45447)

**Comment by KashifKhaan** [comment] 2024-11-28 16:19
The issue might be due to the **Matching rules** and **Deduplications rules** are still refreshing. If you wait for the refresh process to complete, the Preview button should become active.
Please see the screenshots, as I can see the preview button is active.

![image](https://github.com/user-attachments/assets/2fa22d33-6f6c-4665-b229-2b5f3af8d745)

**Comment by a-ainamdar** [comment] 2024-12-10 14:56
Thank you for raising this issue. We will update on this soon. Thank you for your patience!

**Comment by a-ainamdar** [comment] 2024-12-11 14:42
Hi,
This issue is not reproducible . I have waited till all the rules are refreshed.
Preview is not greyed out for me. 
Refer Screenshot below :
![image](https://github.com/user-attachments/assets/a9345a25-f7df-4fdf-a6ef-e7aa830c9423)

**Comment by anjenni** [comment] 2024-12-11 17:50
Closing issue as our tester determined that graying out of Preview button was due to some jobs still running. Preview button will appear when all jobs are complete.

**Closed as completed by anjenni** 2024-12-11 17:50 UTC
